### ISSUE TITLE
Provider not defined

### ISSUE THREAD

**Issue by jacobwise** [vamsii777/directus-extension-bundle-firebase-main#4]
When using this and setting the provider to `firebase` I got an error that the provider was not defined. I could have added in the list of auth providers but that doesn't feel right since we aren't using it to authenticate with directus but as a proxy instead. Am I thinking about that wrong?

**Comment by vamsii777** [comment]
The error you encountered with Firebase as a provider stems from its role as an intermediary rather than a direct authentication provider in Directus. 

Essentially, Firebase verifies users outside Directus, and once confirmed, these users are linked to Directus sessions.

This setup allows Firebase to manage user authentication securely without being embedded within Directus’s internal authentication framework.
